version: '3.8'

services:
  api:
    image: zani-app/zani-server:latest
    container_name: zani-server-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
