name: API Server

on:
  pull_request:
    branches: [ "dev" ]
    types:
      - opened
      - synchronize

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Cache Gradle~
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ### runner application java 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ### application.yml 설정
      - name: Set YML
        run: |
          echo "${{ secrets.APPLICATION_DEV_YML }}" | base64 --decode > ./src/main/resources/application-dev.yml

      ### gradlew 실행 권한 부여
      - name: Grant execute Permission for gradlew
        run: |
          chmod +x gradlew

      ### project build
      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test

