name: Deploy to EC2 using Docker

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t zani-app/zani-server:${{ github.sha }} .
          docker tag zani-app/zani-server:${{ github.sha }} zani-app/zani-server:latest
          docker push zani-app/zani-server:${{ github.sha }}
          docker push zani-app/zani-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull zani-app/zani-server:latest
            docker stop zani-server-container || true
            docker rm zani-server-container || true
            docker run -d -p 8080:8080 --name zani-server-container zani-app/zani-server:latest
